version: "3.7"
services:
  api:
    build: ./app
    container_name: api
    restart: always
    ports:
      - "8081:8081"
  frontend:
    image: httpd:2.4
    container_name: frontend
    volumes:
      - ./frontend/:/usr/local/apache2/htdocs/
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api